### ISSUE TITLE
Agents continue to work on disabled/blacklisted subnets

### ISSUE THREAD

**Issue by mikedamm** [natlas/natlas#150] opened 2019-05-12 02:20 UTC
1. add a large subnet
2. fire up an agent and let it make some progress
3. from the web UI disable/blacklist that subnet
4. agent will continue scanning in that subnet
5. restart server
6. agents will correctly move on to the next subnet

**Comment by 0xdade** [comment] 2019-05-13 00:27
Oh this is peculiar. I've reproduced it and I'll pinpoint the cause. It likely won't get released into another "release" version until I've had some time to fix/implement a few other things, but I'll definitely get this figured out.

**Comment by 0xdade** [comment] 2019-05-13 00:36
I have two networks in scope:

192.168.0.0/24
10.0.0.0/8

When I toggle 10.0.0.0/8 to blacklist, it appears that the scan manager gets updated but somehow is returning only addresses in 10.0.0.0/24.  

@rosswsnider This is happening in your code I think, any ideas what might be causing this?

**Comment by 0xdade** [comment] 2019-05-13 00:51
Turns out it has to do with the IPScanManager [networks](https://github.com/natlas/natlas/blob/master/natlas-server/app/ipscanmanager.py#L5) variable.

I think what's happening is that we're setting the scanmanager to none in the [update](https://github.com/natlas/natlas/blob/master/natlas-server/app/scope.py#L74) and then [reinstantiating it](https://github.com/natlas/natlas/blob/master/natlas-server/app/scope.py#L76), but it's retaining some information about the self.networks value. While I'm not entirely sure how or why, the problem vanishes when I explicitly set `self.networks = []` in the `__init__`. I think it gets locked down to the `/24` in my case because the actual networks it goes through (192.168.0.0/24) during instantiation is only a `/24`, so the random number generator only generates numbers inside the `/24` range.

I'll double check this and get a fix pushed into the `v0.6.x` branch this evening. It'll also make it into the `v0.6.4` release, which should happen sometime this week.

**Closed** 2019-09-30 03:52 UTC
Labels: bug, server
