### ISSUE TITLE
Blacklist IP Tagging not working

### ISSUE THREAD

**Issue by sdupreez** [natlas/natlas#206] opened 2019-10-24 19:28 UTC
**Affecting:** 
Server

**Version:** 
0.6.7

**Describe the bug**
When attempting to tag an IP that is part of the Black List, nothing happens. The tag modal never appears and you are unable to tag black list entries.

**To Reproduce**
1.Go to /admin
2.Choose the Blacklist tab
3.Add entries into Blacklist
4.Click 3 vertical dots next to a Blacklist item
5.From the pop-up menu, choose Tag

**Expected behavior**
One would expect a modal to pop-up, that would allow you to tag an entry in the Blacklist, making use of pre-configured / added tags.

**Screenshots**
As nothing happens when clicking the button, no screenshot is available.

**Comment by 0xdade** [comment] 2019-10-25 06:57
First, thanks for opening this issue! Welcome to the natlas community.

Good find, I'm not sure how this happened. Generally speaking there shouldn't be much use case for tagging blacklist items after they are already added to the blacklist, since blacklist items shouldn't ever show up in scan results. But I would agree that this is unexpected behavior. I committed a potential fix for this on my fork but I'm not in a place where I can currently test/confirm it for the next few days, so it won't make it upstream until early next week at the earliest.

**Closed** 2019-11-02 04:11 UTC
Labels: bug, server
