### ISSUE TITLE
Request Screenshot Instead of Full Scan

### ISSUE THREAD

**Issue by uBadRequest** [natlas/natlas#473] opened 2020-09-01 13:43 UTC
**Describe the feature you'd like**
Instead of requesting a full scan to be conducted, just have the ability to request a screenshot.

**Have you considered alternative ways to get this feature**
Nope

**Additional context**
Sometimes it seems like requesting a re-scan still doesn't get a screenshot, so maybe if we could just specifically request aquatone to take screenshots we would get better results?

**Comment by 0xdade** [comment] 2020-09-01 16:17
If a screenshot isn't being retrieved, try adjusting the web screenshot timeout. Natlas scans represent a point in time, and offering the ability to decouple activities isn't likely to happen because it fundamentally breaks the way documents are stored and the point-in-time snapshot philosophy. Try running aquatone against the thing missing screenshots and see how long it takes. Alternatively try taking the screenshot directly with chrome headless. There are probably some more configuration knobs we can add in to make screenshots more reliable, but I think ultimately it's going to come down to timeouts every time. 

On September 1, 2020 6:44:07 AM PDT, BadRequests <notifications@github.com> wrote:
>**Describe the feature you'd like**
>Instead of requesting a full scan to be conducted, just have the
>ability to request a screenshot.
>
>**Have you considered alternative ways to get this feature**
>Nope
>
>**Additional context**
>Sometimes it seems like requesting a re-scan still doesn't get a
>screenshot, so maybe if we could just specifically request aquatone to
>take screenshots we would get better results?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/natlas/natlas/issues/473

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 0xdade** [comment] 2020-09-03 18:41
Going to close this one as well, the topic of the issue isn't something that fits the vision for the project at this time.

**Closed by 0xdade** 2020-09-03 18:41 UTC
Labels: enhancement, server
